### ISSUE TITLE
RFOSSCore Missing

### ISSUE THREAD

**Issue by batwolf** [gradylorenzo/RocketFOSS#1]
I'm having this issue, is the RFOSSCore file missing?

> Assets/RFOSSCore/Spaces/Scripts/TESTPlanetaryArrangement.cs(3,17): error CS0234: The type or namespace name 'Constants' does not exist in the namespace 'RFOSSCore' (are you missing an assembly reference?)

**Comment by cmdrflexo** [comment]
`PhysicsConstants` was just a struct to hold any precise constants. never ended up putting anything other than gravity:
```CSharp
namespace RFOSSCore.Constants {
	public struct PhysicsConstants {
		public const double g = 6.674e-11;
		
	}
}
```
https://github.com/cmdrflexo/RocketFOSS/blob/master/Assets/RFOSSCore/Physics/PhysicsConstants

**Comment by batwolf** [comment]
Thanks so much!

**Comment by gradylorenzo** [comment]
This is the first time I've gotten an email like this from GitHub, and I
was thoroughly confused
